"""Build TAXA_AU, SPOODEX's checklist of Australian jumping spider genera (HANDOVER §5 "checklist", spec §3.1).

The taxonomy rule (owner's): the checklist is the genera recorded on iNaturalist in Australia, plus the genera in the owner's
Lucid key (Identification aid). iNat names win; the Lucid key is second. The Australian Faunal Directory (AFD, via ALA's BIE)
is used only to map museum spellings onto those names and to read each genus's authority. A name that is only in the AFD is
reported as excluded and never enters the checklist.

Usage (from the repo root):
  python tools/taxa.py                    # print the counts and the constant
  python tools/taxa.py --write            # also replace the TAXA_AU block in spoodex.html
  python tools/taxa.py --lucid PATH       # read the Lucid schema from a local file instead of GitHub
Not shipped with the site: spoodex.html only carries the generated constant.
"""
import json, sys, time, urllib.request, urllib.parse, re

INAT_TREE = 'https://api.inaturalist.org/v1/observations/taxonomy?taxon_id=48139&place_id=6744&verifiable=true'
LUCID = 'https://raw.githubusercontent.com/Themoojuice/Identification-aid/main/01_lucid_schema.json'
AFD = 'https://bie-ws.ala.org.au/ws/childConcepts/' + urllib.parse.quote(
    'https://biodiversity.org.au/afd/taxa/2ebc0b30-7e20-4170-a4a0-035ec32f3944', safe='')
# AFD spelling -> checklist name (owner-approved mappings only)
AFD_MAP = {'Ancepitilobus': 'Ancipitilobus'}
BEGIN, END = '// TAXA_AU:begin', '// TAXA_AU:end'


def get(url):
    req = urllib.request.Request(url, headers={'User-Agent': 'SPOODEX tools/taxa.py (github.com/Themoojuice/spoodex)'})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode('utf-8'))


def main(argv):
    lucid_path = argv[argv.index('--lucid') + 1] if '--lucid' in argv else None
    tree = get(INAT_TREE)
    inat = {t['name']: t['id'] for t in tree['results'] if t.get('rank') == 'genus'}
    time.sleep(1.1)
    schema = json.load(open(lucid_path, encoding='utf-8')) if lucid_path else get(LUCID)
    # Lucid names carry their authority: "Abracadabrella Zabka, 1991"
    lucid = {}
    for t in schema['taxa']:
        if t.get('rank') != 'genus':
            continue
        name, _, auth = t['name'].strip().partition(' ')
        lucid[name] = auth.strip()
    time.sleep(1.1)
    afd_raw = [c for c in get(AFD) if (c.get('rankString') or c.get('rank') or 'genus').lower() == 'genus']
    afd = {}
    for c in afd_raw:
        n = c['name']
        auth = (c.get('nameComplete') or n)[len(n):].strip() or (c.get('author') or '').strip()
        afd[AFD_MAP.get(n, n)] = {'spelling': n, 'auth': auth}

    names = sorted(set(inat) | set(lucid))
    rows = []
    for n in names:
        a = afd.get(n, {})
        rows.append({'n': n, 'inat': inat.get(n), 'lucid': n in lucid, 'afd': [a['spelling']] if a else [],
                     'a': a.get('auth') or lucid.get(n) or ''})

    never = [r['n'] for r in rows if r['inat'] is None]
    inat_only = [r['n'] for r in rows if r['inat'] is not None and not r['lucid']]
    excluded = sorted(a['spelling'] for k, a in afd.items() if k not in set(names))
    no_afd = [r['n'] for r in rows if not r['afd']]
    mapped = sorted(f"{a['spelling']} -> {k}" for k, a in afd.items() if a['spelling'] != k)

    print(f'iNat genera in Australia (verifiable): {len(inat)}')
    print(f'Lucid key genera: {len(lucid)}')
    print(f'AFD genera: {len(afd_raw)}')
    print(f'TAXA_AU (iNat ∪ Lucid): {len(rows)}')
    print(f'Never on iNat in Australia ({len(never)}): {", ".join(never)}')
    print(f'iNat only, not in the Lucid key ({len(inat_only)}): {", ".join(inat_only)}')
    print(f'AFD only, excluded ({len(excluded)}): {", ".join(excluded)}')
    print(f'In the checklist but not in the AFD ({len(no_afd)}): {", ".join(no_afd)}')
    print(f'AFD spellings mapped: {", ".join(mapped) or "none"}')

    js = lambda v: json.dumps(v, ensure_ascii=False).replace('"', "'")
    body = ',\n'.join('  {' + f"n:{js(r['n'])}, inat:{r['inat'] if r['inat'] is not None else 'null'}, lucid:{'true' if r['lucid'] else 'false'}, "
                      f"afd:{js(r['afd'])}, a:{js(r['a'])}" + '}' for r in rows)
    stamp = time.strftime('%Y-%m-%d')
    block = (f"{BEGIN} (generated by tools/taxa.py on {stamp}; edit the script, not this list)\n"
             f"const TAXA_AU = [\n{body},\n];\n"
             f"const TAXA_AU_EXCLUDED = {js(excluded)};   // AFD-only names, shown to the owner in Settings → Taxonomy review\n"
             f"{END}")
    if '--write' in argv:
        path = 'spoodex.html'
        s = open(path, encoding='utf-8').read()
        i, j = s.find(BEGIN), s.find(END)
        if i < 0 or j < 0:
            sys.exit(f'{path}: no {BEGIN} … {END} block to replace')
        s = s[:i] + block + s[j + len(END):]
        open(path, 'w', encoding='utf-8', newline='\n').write(s)
        print(f'Wrote {len(rows)} genera into {path}')
    else:
        print()
        print(block)


if __name__ == '__main__':
    main(sys.argv[1:])
